# Generated by Django 3.0.9 on 2021-12-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_auto_20211124_0837'),
        ('pedidos', '0002_auto_20211119_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerdaTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Perda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField()),
                ('comentario', models.CharField(max_length=500)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.Lojas')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.GrupoProduto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.PerdaTipo')),
            ],
        ),
    ]
