# Generated by Django 3.0.9 on 2021-12-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_perda_perdatipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdatipo',
            name='flag_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
