# Generated by Django 3.0.9 on 2022-01-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDeEntregaBloqueado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mes', models.PositiveSmallIntegerField(blank=True, choices=[('', 'Selecione o mês'), (1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True)),
                ('data_bloqueio', models.DateField()),
                ('dia_mes', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
