# Generated by Django 3.0.9 on 2022-01-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=150)),
                ('observacoes', models.CharField(blank=True, max_length=300, null=True)),
                ('flag_ativo', models.BooleanField(default=True)),
                ('pre_selecionada', models.BooleanField(default=False, help_text='Se marcado, essa categoria aparecerá pré selecionada na tela de pedidos.')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=150)),
                ('flag_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100)),
                ('flag_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=150)),
                ('flag_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=150)),
                ('flag_ativo', models.BooleanField(default=True)),
                ('unidade_por_lote', models.PositiveIntegerField()),
                ('flag_disponivel', models.BooleanField(default=True)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='lojas.CategoriaProduto')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.Deposito')),
                ('grupo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_relacionados', to='lojas.GrupoProduto')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.Lote')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='TabelaDePreco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=150)),
                ('flag_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabelaDePrecoItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('flag_ativo', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.Produto')),
                ('tabela_de_preco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='lojas.TabelaDePreco')),
            ],
        ),
        migrations.CreateModel(
            name='Lojas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome_da_loja', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=100)),
                ('razao_social', models.CharField(max_length=500)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=500, null=True)),
                ('telefone', models.BigIntegerField()),
                ('telefone_2', models.BigIntegerField(blank=True, null=True)),
                ('cep', models.IntegerField()),
                ('cidade', models.CharField(max_length=150)),
                ('uf', models.CharField(max_length=2)),
                ('endereco', models.CharField(max_length=300)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('flag_ativo', models.BooleanField(default=True)),
                ('pedido_minimo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dias_de_entrega', models.CharField(max_length=50)),
                ('flag_loja_propria', models.BooleanField(default=False)),
                ('produtos_bloqueados', models.ManyToManyField(blank=True, null=True, related_name='lojas', to='lojas.Produto')),
                ('tabela_de_preco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lojas.TabelaDePreco')),
            ],
            options={
                'ordering': ('nome_da_loja',),
            },
        ),
    ]
