# Generated by Django 3.0.9 on 2021-11-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproduto',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='lojas.CategoriaProduto'),
        ),
    ]
