# Generated by Django 3.0.9 on 2021-12-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_auto_20211124_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproduto',
            name='pre_selecionada',
            field=models.BooleanField(default=False, help_text='Se marcado, essa categoria aparecerá pré selecionada na tela de pedidos.'),
        ),
    ]
