# Generated by Django 3.0.9 on 2021-11-19 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0001_initial'),
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contagemformularios',
            name='usuario_preenchimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contagem',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contagens', to='lojas.Lojas'),
        ),
        migrations.AddField(
            model_name='contagem',
            name='usuario_criacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configformulariodecontagemcategorias',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.CategoriaProduto'),
        ),
        migrations.AddField(
            model_name='configformulariodecontagemcategorias',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_do_formulario', to='estoque.ConfigFormularioDeContagem'),
        ),
    ]
