# Generated by Django 3.0.9 on 2021-11-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='config_caixa_selecao',
            field=models.BooleanField(default=False),
        ),
    ]
