# Generated by Django 3.0.9 on 2022-01-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('flag_ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('ultima_atualizacao', models.DateTimeField()),
                ('status', models.CharField(default='Pendente', max_length=30)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='lojas.Lojas')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioFormulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Formulario')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='inventario.Inventario')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeContagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('flag_ativo', models.BooleanField(default=True)),
                ('formularios', models.ManyToManyField(to='inventario.Formulario')),
                ('lojas', models.ManyToManyField(blank=True, null=True, related_name='tipos_de_contagens', to='lojas.Lojas')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.InventarioFormulario')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_do_inventario', to='inventario.Inventario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.GrupoProduto')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo_de_contagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.TipoDeContagem'),
        ),
    ]
