# Generated by Django 3.0.9 on 2021-12-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_auto_20211124_0837'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='itens',
            field=models.ManyToManyField(to='lojas.GrupoProduto'),
        ),
        migrations.CreateModel(
            name='TipoDeContagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('formularios', models.ManyToManyField(to='inventario.Formulario')),
            ],
        ),
    ]
