# Generated by Django 3.0.9 on 2021-12-05 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojas', '0002_auto_20211124_0837'),
        ('inventario', '0003_tipodecontagem_lojas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='lojas.Lojas')),
                ('tipo_de_contagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.TipoDeContagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Formulario')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_do_inventario', to='inventario.Inventario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.GrupoProduto')),
            ],
        ),
    ]
