# Generated by Django 3.0.9 on 2021-12-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_inventario_inventarioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True, default='2021-01-01 10:00:00'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InventarioFormulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Formulario')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='inventario.Inventario')),
            ],
        ),
        migrations.AlterField(
            model_name='inventarioitem',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.InventarioFormulario'),
        ),
    ]
