# Generated by Django 3.0.9 on 2021-12-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20211205_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='ultima_atualizacao',
            field=models.DateTimeField(default='2021-12-05 10:00:00'),
            preserve_default=False,
        ),
    ]
