# Generated by Django 3.0.9 on 2021-12-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_inventario_ultima_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='status',
            field=models.CharField(default='Aberto', max_length=30),
        ),
    ]
