# Generated by Django 3.0.9 on 2021-12-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20211205_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='flag_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipodecontagem',
            name='flag_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
